# Generated by Django 6.0.6 on 2026-06-16 15:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Доменное имя (например, company.ru)', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Введите корректное доменное имя', regex='^[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')])),
                ('owner', models.CharField(help_text='Ответственный сотрудник', max_length=150)),
                ('criticality', models.CharField(choices=[('Low', 'Низкий'), ('Medium', 'Средний'), ('High', 'Высокий')], default='Medium', help_text='Уровень критичности', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Мониторинг включён')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Корпоративный домен',
                'verbose_name_plural': 'Корпоративные домены',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BreachRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breach_name', models.CharField(help_text='Название утечки', max_length=150)),
                ('breach_date', models.DateField(help_text='Дата утечки')),
                ('data_classes', models.TextField(help_text='Типы скомпрометированных данных')),
                ('accounts_count', models.PositiveIntegerField(default=0, help_text='Количество затронутых аккаунтов')),
                ('source', models.CharField(default='HaveIBeenPwned', help_text='Источник информации', max_length=100)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaches', to='monitor.corporatedomain')),
            ],
            options={
                'verbose_name': 'Запись об утечке',
                'verbose_name_plural': 'Записи об утечках',
                'ordering': ['-breach_date'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Clean', 'Чисто'), ('Warning', 'Предупреждение'), ('Critical', 'Критично')], default='Clean', max_length=10)),
                ('breaches_found', models.PositiveIntegerField(default=0)),
                ('risk_comment', models.TextField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='monitor.corporatedomain')),
            ],
            options={
                'verbose_name': 'Журнал проверки',
                'verbose_name_plural': 'Журналы проверок',
                'ordering': ['-checked_at'],
            },
        ),
    ]
