# Generated by Django 6.0.6 on 2026-06-16 19:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(help_text='System ID для формирования ссылки', max_length=100)),
                ('storage_id', models.CharField(blank=True, help_text='ID для доступа к содержимому файла через /file/read', max_length=255)),
                ('name', models.CharField(blank=True, help_text='Название или заголовок записи', max_length=255)),
                ('xscore', models.IntegerField(help_text='Релевантность (0-100). Показывает вероятность реальной угрозы', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('bucket', models.CharField(help_text='Тип базы (например, pastes, darknet.tor, leaks.public)', max_length=100)),
                ('media_type', models.CharField(help_text='Человекочитаемый тип контента (Paste, PDF, и т.д.)', max_length=50)),
                ('size', models.PositiveIntegerField(default=0, help_text='Размер данных в байтах')),
                ('date_found', models.DateTimeField(help_text='Дата оригинальной записи или индексации')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='Когда наша система нашла эту запись')),
                ('verification', models.ForeignKey(help_text='Связанная проверка', on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='monitor.verificationlog')),
            ],
            options={
                'verbose_name': 'Деталь угрозы IntelX',
                'verbose_name_plural': 'Детали угроз IntelX',
                'ordering': ['-xscore', '-date_found'],
                'indexes': [models.Index(fields=['-xscore'], name='monitor_thr_xscore_8142bb_idx'), models.Index(fields=['bucket'], name='monitor_thr_bucket_96fc81_idx')],
            },
        ),
    ]
